### ISSUE TITLE
Need of root right to query SNMP? (and wrong plugin name in logs)

### ISSUE THREAD

**Issue by BadWolf42** [hugoKs3/plugin-brother#16]
Hello,

Nice plugin, thanks!

But there is no need of SUDO here and wrong plugin name (No-Ip) in logs:
https://github.com/hugoKs3/plugin-brother/blob/439322d3170e40207b443f013d21b3ad57e31d32/core/class/brother.class.php#L207

I did not PR as removing the sudo implies removing the file before to avoid right issues: buffer file was previously created with root user so file needs to be removed before sudo can be removed.

For information, using a blocking SNMP query stalles the interface of Jeedom on save and refresh, especially if the printer is offline.
Could you consider putting content of `pullBrother()` in an immediately run cron?

By the way the "No-Ip" plugin name is still present here:
https://github.com/hugoKs3/plugin-brother/blob/439322d3170e40207b443f013d21b3ad57e31d32/core/class/brother.class.php#L208

https://github.com/hugoKs3/plugin-brother/blob/9c99b5d75e6406744d88ccd30c41d956cb6383cc/core/class/brother.class.php#L432

Thanks,
Bad

**Comment by hugoKs3** [comment]
Hello Bad,

Thanks for the feedback and suggestions. Starting to implement them.
Question for buffer file: not sure what you mean by "removing the file before being sudo can be removed". Which file are you talking about? Where is located the buffer file you are talking about?

Thank you.

**Comment by BadWolf42** [comment]
Hello,

I was in a hurry this morning, that's why it makes no sense :]

I'm talking about file `plugins/brother/data/output.json`, which should hold the json formatted SNMP collected data from printer.
If you remove `sudo` and this file exists, then next time the plugin will try to overwrite it, it will fail, as owner is root.
So you may need to `chown` this file when the plugin is upgraded (using sudo...)

Is it more clear ? ;)

**Comment by hugoKs3** [comment]
Crystal clear! Thanks ;)

**Comment by hugoKs3** [comment]
Nouvelle version **beta** publiée avec vos suggestions
